### PR TITLE
Move CREATE DB script to main sql file

### PR DESCRIPTION
**Pull request by thebenlamm**

### CODE REVIEW

**Comment by thebenlamm** [comment]
I just the create db line from it's .sql file to the main .sql file

**Comment by amiyrb** [comment]
For me to access this should I pull it from the upstream?

**Comment by amiyrb** [comment]
I merged the two branches and now I think some of my files are locked in netbeans I can't make changes to them

**Comment by amiyrb** [comment]
Strangely I'm still having that problem where the file is locked in netbeans but thats not the file I'm working in right now as for the drop down I created a drop down for books I'm still looking for querying the databse

**Pull request merged**
